baseurl = "https://nubeblog.com/"
publishDir = "docs"

languageCode = "es-es"
title = "Nubeblog"
summerization = "html_firstparagraph"
paginate = 9
theme = "hyde-hyde"

# Google analytics
gravatarHash = "0a6b102fdb89dfdabc76f654d955a0b5"
googleAnalytics = "UA-5807955-1"


[permalinks]
  post = "/post/:year/:month/:day/:slug"
  project = "/project/:year/:month/:day/:slug"

[indexes]
  tag = "tags"
  topic = "categories"

[params]
  mainSections = ["post"]
  # Warning Keys are case sensitives
  Subtitle = "Un blog sobre cosas de Cloud Computing y eso"
  description = "Se単or de Logro単o que hace cosas con ordenadores y programas."
  cover = "/images/cover.jpg"

  postNavigation = true
  relatedPosts = true

[params.social]
  twitter = "nubeblog"
  github = "diegoparrilla"
  facebook = "dparrilla"
  linkedin = "diegoparrilla"
  gravatar = "diego.parrilla.santamaria@gmail.com"
  
[author]
  FirstName = "Diego"
  LastName = "Parrilla"
  Gender = "male"
  UserName = "nubeblog"
  Image = "//www.gravatar.com/avatar/0a6b102fdb89dfdabc76f654d955a0b5.png"
  Bio = "Se単or de Logro単o que hace cosas con ordenadores y programas."
  Website = "https://nubeblog.com"

[[menu.main]]
  name = " Todos los posts"
  identifier = "post"
  url = "/post/"
  
[[menu.main]]
  name = "Sobre mi"
  identifier = "sobre-mi"
  url = "https://www.linkedin.com/in/diegoparrilla/"

[[menu.main]]
  name = "About me"
  identifier = "about"
  url = "https://www.linkedin.com/in/diegoparrilla/"
